# Generated by Django 3.0.3 on 2020-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=100, null=True),
        ),
    ]
