# Generated by Django 3.0.3 on 2020-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200620_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
