# Generated by Django 3.0.3 on 2020-06-20 10:33

from django.db import migrations, models
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20200620_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='leave_file',
            field=models.FileField(null=True, upload_to=leave.models.user_directory_path),
        ),
    ]
