# Generated by Django 3.0.3 on 2020-06-22 06:57

from django.db import migrations, models
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_studentleave_leave_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='leave_file',
            field=models.FileField(null=True, upload_to=leave.models.employee_user_directory_path),
        ),
    ]
