# Generated by Django 3.0.3 on 2020-05-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200518_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feecategory',
            old_name='submisstion_mode',
            new_name='submission_mode',
        ),
    ]
