# Generated by Django 3.0.3 on 2020-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20200518_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feecycle',
            old_name='firstSubmissionDate',
            new_name='last_submission_date',
        ),
        migrations.RenameField(
            model_name='feecycle',
            old_name='lastSubmissionDate',
            new_name='starting_month',
        ),
        migrations.AddField(
            model_name='feecycle',
            name='session',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feecycle',
            name='cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quaterly'), ('yearly', 'Yearly')], default='yearly', max_length=50),
        ),
    ]
