# Generated by Django 3.0.3 on 2020-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20200518_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
