# Generated by Django 3.0.3 on 2020-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
