# Generated by Django 3.0.3 on 2020-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_auto_20200518_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecycle',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.Session'),
        ),
    ]
