# Generated by Django 3.0.3 on 2020-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_auto_20200518_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecycle',
            name='starting_month_i',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
    ]
