# Generated by Django 3.0.3 on 2020-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_feecycle_starting_month_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecycle',
            name='starting_month',
        ),
    ]
