# Generated by Django 3.0.3 on 2020-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_remove_feecycle_starting_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feecycle',
            old_name='starting_month_i',
            new_name='starting_month',
        ),
    ]
