# Generated by Django 3.0.3 on 2020-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_remove_feecycle_last_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecycle',
            name='last_submission_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
