# Generated by Django 3.0.3 on 2020-05-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0001_initial'),
        ('fees', '0013_feecycle_last_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.FeeCategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.Session')),
            ],
            options={
                'unique_together': {('fee_category', 'session')},
            },
        ),
        migrations.CreateModel(
            name='ClassFeeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='classform.ClassRoom')),
                ('fee_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_configs', to='fees.FeeConfiguration')),
            ],
            options={
                'unique_together': {('fee_configuration', 'classroom')},
            },
        ),
    ]
