# Generated by Django 3.0.3 on 2020-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0001_initial'),
        ('fees', '0015_auto_20200519_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconfiguration',
            name='classrooms',
            field=models.ManyToManyField(related_name='fee_configurstions', to='classform.ClassRoom'),
        ),
    ]
