# Generated by Django 3.0.3 on 2020-05-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_feeconfiguration_classrooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassFeeConfiguration',
        ),
    ]
