# Generated by Django 3.0.3 on 2020-05-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_delete_classfeeconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feediscount',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='discount',
            field=models.IntegerField(verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='total_off',
            field=models.IntegerField(verbose_name='Discount (Total off)'),
        ),
    ]
