# Generated by Django 3.0.3 on 2020-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0018_auto_20200520_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feediscount',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='total_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount (Total off)'),
        ),
    ]
