# Generated by Django 3.0.3 on 2020-05-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0019_auto_20200520_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feediscount',
            name='student',
        ),
    ]
