# Generated by Django 3.0.3 on 2020-05-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_remove_feediscount_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feediscount',
            old_name='discount',
            new_name='percentage',
        ),
    ]
