# Generated by Django 3.0.3 on 2020-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_auto_20200520_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feediscount',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
