# Generated by Django 3.0.3 on 2020-05-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0022_auto_20200520_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='feediscount',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.Session'),
            preserve_default=False,
        ),
    ]
