# Generated by Django 3.0.3 on 2020-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_auto_20200520_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feediscount',
            name='category',
        ),
        migrations.AddField(
            model_name='feediscount',
            name='category',
            field=models.ManyToManyField(related_name='discounts', to='fees.FeeCategory'),
        ),
    ]
