# Generated by Django 3.0.3 on 2020-05-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0026_auto_20200520_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='feediscount',
            name='fee_categories',
            field=models.ManyToManyField(related_name='discounts', to='fees.FeeCategory'),
        ),
        migrations.RemoveField(
            model_name='feediscount',
            name='category',
        ),
        migrations.AddField(
            model_name='feediscount',
            name='category',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
