# Generated by Django 3.0.3 on 2020-05-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0027_auto_20200520_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feediscount',
            old_name='category',
            new_name='discount_category',
        ),
    ]
