# Generated by Django 3.0.3 on 2020-05-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0029_studentdiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdiscount',
            old_name='classroom_student',
            new_name='classroom_students',
        ),
    ]
