# Generated by Django 3.0.3 on 2020-05-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0001_initial'),
        ('fees', '0030_auto_20200521_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHeadMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('classroom_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
                ('fee_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.FeeConfiguration')),
            ],
        ),
    ]
