# Generated by Django 3.0.3 on 2020-05-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0032_auto_20200523_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeheadmapping',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeheadmapping',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.FeeCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeheadmapping',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.Session'),
            preserve_default=False,
        ),
    ]
