# Generated by Django 3.0.3 on 2020-05-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0033_auto_20200525_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeheadmapping',
            name='fee_configuration',
        ),
    ]
