# Generated by Django 3.0.3 on 2020-05-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0034_remove_feeheadmapping_fee_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeheadmapping',
            name='fee_configuration_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fee_head_mappings', to='fees.FeeConfiguration'),
            preserve_default=False,
        ),
    ]
