# Generated by Django 3.0.3 on 2020-05-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0035_feeheadmapping_fee_configuration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeheadmapping',
            name='fee_configuration_name',
        ),
        migrations.RemoveField(
            model_name='feeheadmapping',
            name='session',
        ),
    ]
