# Generated by Django 3.0.3 on 2020-05-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0036_auto_20200525_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeheadmapping',
            name='fee_configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.FeeConfiguration'),
            preserve_default=False,
        ),
    ]
