# Generated by Django 3.0.3 on 2020-05-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('fees', '0037_feeheadmapping_fee_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeheadmapping',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_head_mappings', to='form.StudentInfo'),
        ),
    ]
