# Generated by Django 3.0.3 on 2020-05-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0038_auto_20200526_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feediscount',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='fees.Session'),
        ),
    ]
