# Generated by Django 3.0.3 on 2020-06-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('fees', '0040_auto_20200526_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscountThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=10)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.StudentDiscount')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.StudentInfo')),
            ],
        ),
    ]
