# Generated by Django 3.0.3 on 2020-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0041_studentdiscountthrough'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdiscount',
            name='student',
        ),
    ]
