# Generated by Django 3.0.3 on 2020-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('fees', '0042_remove_studentdiscount_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscount',
            name='student',
            field=models.ManyToManyField(related_name='fee_discounts', through='fees.StudentDiscountThrough', to='form.StudentInfo'),
        ),
    ]
