# Generated by Django 3.0.3 on 2020-06-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('fees', '0044_auto_20200605_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscountthrough',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='form.StudentInfo'),
        ),
    ]
