# Generated by Django 3.0.3 on 2020-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0045_auto_20200605_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feecycle',
            unique_together={('cycle', 'session')},
        ),
    ]
