# Generated by Django 3.0.3 on 2020-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0046_auto_20200612_1113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feecycle',
            unique_together=set(),
        ),
    ]
