# Generated by Django 3.0.3 on 2020-06-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('fees', '0049_feestatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestatus',
            unique_together={('student', 'session', 'month')},
        ),
    ]
