# Generated by Django 3.0.3 on 2020-06-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200617_2343'),
        ('fees', '0050_auto_20200613_1249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestatus',
            unique_together={('student', 'session')},
        ),
    ]
