# Generated by Django 3.0.6 on 2020-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
