# Generated by Django 3.0.3 on 2020-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200803_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('SuperAdmin', 'Super admin'), ('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='TH', max_length=10),
        ),
    ]
