# Generated by Django 3.0.3 on 2020-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markssection', '0002_skill_studentskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentskill',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
