# Generated by Django 3.0.3 on 2020-06-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0045_auto_20200605_1315'),
        ('markssection', '0003_auto_20200615_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskill',
            name='session',
        ),
        migrations.AddField(
            model_name='skill',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.Session'),
        ),
    ]
