# Generated by Django 3.0.3 on 2020-06-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markssection', '0004_auto_20200615_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='examName',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='markssection.Exam'),
        ),
    ]
