# Generated by Django 3.0.3 on 2020-05-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeform', '0001_initial'),
        ('classform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomSubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeform.Teacher')),
            ],
        ),
    ]
