# Generated by Django 3.0.3 on 2020-05-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeform', '0001_initial'),
        ('classform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('available_casual_leave', models.IntegerField(default=10)),
                ('available_sick_leave', models.IntegerField(default=10)),
                ('taken_casual_leave', models.IntegerField(default=0)),
                ('taken_sick_leave', models.IntegerField(default=0)),
                ('total_no_of_days_present', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeform.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('available_casual_leave', models.IntegerField(default=10)),
                ('available_sick_leave', models.IntegerField(default=10)),
                ('taken_casual_leave', models.IntegerField(default=0)),
                ('taken_sick_leave', models.IntegerField(default=0)),
                ('total_no_of_days_present', models.IntegerField(default=0)),
                ('total_no_of_days_late', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
            ],
        ),
    ]
