# Generated by Django 3.0.3 on 2020-06-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20200619_1654'),
        ('attendence', '0002_auto_20200623_0021'),
    ]

    operations = [
    ]
