# Generated by Django 3.0.3 on 2020-05-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
                ('holiday_date_to', models.DateField(default=models.DateField())),
                ('employeeholiday', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays_class', to='classform.ClassRoom')),
            ],
        ),
    ]
