# Generated by Django 3.0.3 on 2020-05-16 14:24

from django.db import migrations, models
import django.db.models.deletion
import transport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_route_code', models.CharField(max_length=110, unique=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('route_distance', models.IntegerField(null=True)),
                ('start_place', models.CharField(max_length=30)),
                ('end_place', models.CharField(max_length=30)),
                ('archived', models.BooleanField(blank=True, null=True)),
                ('start_lattitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('start_longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('end_lattitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('end_longitude', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeID', models.AutoField(primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=110, unique=True)),
                ('archived', models.BooleanField(blank=True, null=True)),
                ('shift_time', models.CharField(choices=[('afternoon', 'Afternoon'), ('morning', 'Morning'), ('both', 'Both')], default='morning', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('service_id', models.BigIntegerField()),
                ('no_of_seat', models.IntegerField()),
                ('maximum_allowed', models.IntegerField()),
                ('vehicle_type', models.CharField(default='', max_length=30)),
                ('insurance_company', models.CharField(default='', max_length=30)),
                ('contact_person', models.CharField(blank=True, default='', max_length=30)),
                ('insurance_date', models.DateField(blank=True, null=True)),
                ('permit_valid_date', models.DateField(blank=True, null=True)),
                ('pollution_cert_exp_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('fitness_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppage_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lattitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('route_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppagess', to='transport.RouteDetail')),
            ],
        ),
        migrations.AddField(
            model_name='routedetail',
            name='route_code_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_shift', to='transport.Routes'),
        ),
        migrations.AddField(
            model_name='routedetail',
            name='route_code_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_shift', to='transport.Routes'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeform.Employee')),
                ('license_no', models.BigIntegerField()),
                ('batch_no', models.BigIntegerField()),
                ('driverPic', models.FileField(null=True, upload_to=transport.models.user_directory_path, verbose_name='Driver Picture')),
                ('driverLicense', models.FileField(upload_to=transport.models.user_directory_path, verbose_name='Driver License')),
                ('driverID', models.FileField(null=True, upload_to=transport.models.user_directory_path, verbose_name='Driver Name')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RouteVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.Routes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.Vehicle')),
            ],
            options={
                'unique_together': {('route', 'vehicle')},
            },
        ),
    ]
