# Generated by Django 3.0.3 on 2020-05-16 14:24

from django.db import migrations, models
import schoolinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('schoolName', models.CharField(max_length=100)),
                ('addresss', models.CharField(max_length=100)),
                ('principalName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('schoolID', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('contactNumber', models.IntegerField()),
                ('webSiteURL', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to=schoolinfo.models.user_directory_path)),
                ('logo', models.FileField(upload_to=schoolinfo.models.user_directory_path)),
            ],
        ),
    ]
